package com.csair.mts.domain.email;
import java.security.Security;
import java.util.Date;
import java.util.Properties;
 

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
 
public class SendMail {
	
	public static final String username = "1";
	public static final String password = "1";
	public static final String messageSubject = "Test E-mail Job";
	public static final String messageContent = "How are you?\n\rThis is a test E-mail generated by the quartz scheduler. ";
	public static final String recepient = "2@localhost";
	
    @SuppressWarnings("restriction")
	public static void sendMail(String sendUser,String sendUserName,String sendPwd,String valueSMTP) throws AddressException,
            MessagingException {
        String SEND_USER = sendUser;
        String SEND_UNAME = sendUserName;
        String SEND_PWD = sendPwd;
        String VALUE_SMTP = valueSMTP;
        
        //Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        
        Properties props = System.getProperties();
        
        props.setProperty("mail.smtp.host", "localhost");
        
        props.setProperty("mail.smtp.port", "25");
       
        props.put("mail.smtp.auth", "true");
 
        Session session = Session.getDefaultInstance(props,
                new Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
 
        // -- Create a new message --
        session.setDebug(true);
        Message msg = new MimeMessage(session);
 
        // -- Set the FROM and TO fields --
        msg.setFrom(new InternetAddress(username));
        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(
                recepient, false));
        msg.setSubject(messageSubject);
        msg.setText(messageContent);
        msg.setSentDate(new Date());
        Transport transport = session.getTransport("smtp");
        // smtp验证
        transport.connect(VALUE_SMTP, SEND_UNAME, SEND_PWD);
        // 发送
        transport.sendMessage(msg, msg.getAllRecipients());
        Transport.send(msg);
        transport.close();
 
        System.out.println("Message sent.");
    }
 
}
